name = "sima"
workers_dev = true
main = "./_build/default/bin/node/bin/main.js"
compatibility_date = "2025-01-24"

[observability.logs]
enabled = true

[build]
command = "dune build @@default @ocaml-index"
watch_dir = "bin"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "sima"
database_id = "a3e19729-1ee9-4693-af73-0732eca1d49c"
